title: faraday's garden 🌻
include: ["_pages", "_notes/assets"]
exclude: ["_includes/notes_graph.json"]
# You may need to change the base URL depending on your deploy configuration.
# For Vercel deployment, use the repository name if deployed to a subdirectory
# Leave empty if deployed to root domain
baseurl: ""

# Production URL (set this to your actual Vercel URL)
url: "https://yourdomain.com" # Update this with your actual domain

# If you are using a host that cannot resolve URLs that do
# not end with .html (such as Neocities), set this to 'true'.
# For Vercel, try setting this to 'true' if you get 404 errors
use_html_extension: true

# Set to `true` to open non-internal links in new tabs, or
# set to `false` to open non-internal links in current tab.
open_external_links_in_new_tab: true

# Set to `true` to replace tweet URLs with Twitter embeds.
# Note that doing so will negatively the reader's privacy
# as their browser will communicate with Twitter's servers.
embed_tweets: false

# Set to `true` to replace YouTube URLs with YouTube video embeds.
# This will automatically embed videos from youtube.com and youtu.be links
embed_youtube: true

permalink: pretty
relative_permalinks: false

plugins:
  - jekyll-last-modified-at

sass:
  sass_dir: _sass
  style: :compressed

collections:
  notes:
    output: true
    permalink: /:slug

defaults:
  - scope:
      path: "**/*"
    values:
      layout: "default"
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"
